version: '2'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - $PWD/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
    - $PWD/data/grafana_db:/var/lib/grafana
  zipkin:
    image:  openzipkin/zipkin
    ports:
    - 9411:9411